// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA71MLU3d9n2RgZCsvs2H9HlGHt-6MT_Wo',
    appId: '1:794548833728:web:f19b2b65ca5e44c3bc0c25',
    messagingSenderId: '794548833728',
    projectId: 'fir-64a24',
    authDomain: 'fir-64a24.firebaseapp.com',
    storageBucket: 'fir-64a24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLoR9n4P16Phn9LKPC8HuGjIDxFV961qE',
    appId: '1:794548833728:android:9d9d18ed33d28cd8bc0c25',
    messagingSenderId: '794548833728',
    projectId: 'fir-64a24',
    storageBucket: 'fir-64a24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcytBKHDdKWriOAnzPLQwzv9Myx6pNINE',
    appId: '1:794548833728:ios:e6f491df03d893debc0c25',
    messagingSenderId: '794548833728',
    projectId: 'fir-64a24',
    storageBucket: 'fir-64a24.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcytBKHDdKWriOAnzPLQwzv9Myx6pNINE',
    appId: '1:794548833728:ios:013cada0259ee439bc0c25',
    messagingSenderId: '794548833728',
    projectId: 'fir-64a24',
    storageBucket: 'fir-64a24.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
